version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - chore
    commit-message:
      prefix: chore(deps)
      prefix-development: chore(devdeps)
      include: scope
    groups:
      production-dependencies:
        dependency-type: production
      dev-dependencies:
        dependency-type: development

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - chore
    commit-message:
      prefix: chore(deps)
      include: scope
