import esbuild from "esbuild";
import process from "process";
import { readFileSync, existsSync } from "node:fs";
import { builtinModules } from 'node:module';

const prod = (process.argv[2] === "production");
const clientIdPath = './.oauth-client-id.txt';
const OAUTH_CLIENT_ID = existsSync(clientIdPath)
? readFileSync(clientIdPath, 'utf8').trim()
: '';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
OAuth client ID: ${OAUTH_CLIENT_ID}
*/
`;

const context = await esbuild.context({
banner: {
js: banner,
},
entryPoints: ["src/main.ts"],
bundle: true,
platform: "node",
external: [
"obsidian",
"electron",
"node:*",
"@codemirror/autocomplete",
"@codemirror/collab",
"@codemirror/commands",
"@codemirror/language",
"@codemirror/lint",
"@codemirror/search",
"@codemirror/state",
"@codemirror/view",
"@lezer/common",
"@lezer/highlight",
"@lezer/lr",
...builtinModules],
format: "cjs",
target: "es2018",
logLevel: "info",
sourcemap: prod ? false : "inline",
treeShaking: true,
outfile: "main.js",
minify: prod,
define: {
'process.env.OBSIDIAN_COPILOT_AGENT_CLIENT_ID': JSON.stringify(OAUTH_CLIENT_ID),
},
});

if (prod) {
await context.rebuild();
process.exit(0);
} else {
await context.watch();
}
